### ISSUE TITLE
Cannot load sample project

### ISSUE THREAD

**Issue by evetere-baufest** [scalableminds/play-mongev#3]
Hi,
I cannot get the plugin to work in my app, so I got the sample application. I cannot get activator to load it.
chc@zeus:~/mongev/play-mongev/sample$ activator
[info] Loading project definition from /home/pdg/mongev/play-mongev/sample/project
[error] /home/pdg/mongev/play-mongev/sample/project/Build.scala:3: object Play is not a member of package play
[error] import play.Play.autoImport._
[error]             ^
[error] /home/pdg/mongev/play-mongev/sample/project/Build.scala:4: not found: object PlayKeys
[error] import PlayKeys._
[error]        ^
[error] /home/pdg/mongev/play-mongev/sample/project/Build.scala:16: value enablePlugins is not a member of sbt.Project
[error]   val main = Project(appName, file(".")).enablePlugins(play.PlayScala).settings(
[error]                                          ^
[error] three errors found
[error] (compile:compile) Compilation failed
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by tmbo** [comment]
There was an inconsistency between the sample projects play version and the libraries. I fixed that one, should be working.
